### PR TITLE
Light sensor improvements

### PR DESCRIPTION
**Pull request by SNeele**

### CODE REVIEW

**Comment by maxspahn** [comment]
Can you change the PR's base branch from `master` to `develop`?

**Comment by maxspahn** [comment]
you could have also edited that ;)

**Comment by SNeele** [comment]
I didn't see your original comment, can I change this in this PR, or should I make a new one?

**Comment by maxspahn** [comment]
If it wasn't supposed to be pushed here, than better close it.
Otherwise, you can change it inside the PR.

**Pull request closed without merging**
