### PR TITLE
Ft prius integration

### PR DESCRIPTION
**Pull request by maxspahn**
Integrates prius car into the environment.
It introduces a new type of non-holonomic robot, the `bicycle_model.py`.

### CODE REVIEW

**Review by GijsGroote — COMMENTED** [review]
Quick question: Why is the Prius not clickable/draggable? As in it is not possible to click and drag the Prius around. While this is possible with the pointRobot or boxerRobot for example. With the dual_arm there is some minimal interaction possible using the mouse. Where (and why) is there a distinction between robots allowing to be dragged along the screen and robots which do not allow this.

**Comment by maxspahn** [comment]
Good question on this possible "interaction". To be honest, I don't know why this is the case. It might be related to the collision shape definitions in the urdf files.

**Comment by maxspahn** [comment]
Changes base branch according to #75.

**Comment by GijsGroote** [comment]
I see that while trying to fix a failing test I've accidentally merged the develop branch into ft-prius-intergration. I want to update this by removing my last commit....only...
I've found myself in the detached HEAD state which makes it hard to remove my accident. 
@maxspahn are you able to remove commit e42b80b?

**Comment by maxspahn** [comment]
@GijsGroote You could revert that change with `git reset --hard <commit-hash>`.
However, I think it is actually the right thing to do. 
You want to merge the current state of develop into the feature branch. Otherwise, it would be impossible to accept the PR of the feature branch onto develop.

**Pull request merged**
