### PR TITLE
ft[sensors]: Gives FullSensor access to all attributes of environment.

### PR DESCRIPTION
**Pull request by maxspahn**
Adresses #159.
Replaces sensing from pybullet through indices by accessing environment items directly.
Splits unittest for sensors into separate files.

### CODE REVIEW

**Review by c-salmi — APPROVED** [review]
Looks good :+1:  So the FullSensor will sense all obstacles that are of type or inherit type `CollisionObstacle` and are created with the `env.add_obstacle()` method. But it doesn't support obstacles that are added directly to pybullet (without calling the method of env) because they are not registered under `self._obsts` in the env. Also obstacles with flag `movable=True` will give wrong sensor data when interacted with I think, right? Maybe we should add this info somewhere in the docs or comments, or add a check for moveable obstacles. But functionality wise I think it's all good!

**Comment by c-salmi** [comment]
Also was thinking maybe it would be better to change the way mpscenes updates the position [here](https://github.com/maxspahn/motion_planning_scenes/blob/d756cc3a4e0e8b7bd36a7e7f429b6de3ccd9a9d0/mpscenes/obstacles/dynamic_obstacle.py#L99) and use the function from pybullet `resetBaseVelocity` to reset to a non-zero velocity, so we could just read from pybullet directly and still support moveable obstacles. What do you think?

**Comment by maxspahn** [comment]
> Also obstacles with flag movable=True will give wrong sensor data when interacted with I think, right?

That is very much true! Good point. For movable obstacle, we cannot rely on the obstacles itself and we should catch this case.

> Also was thinking maybe it would be better to change the way mpscenes updates the position [here](https://github.com/maxspahn/motion_planning_scenes/blob/d756cc3a4e0e8b7bd36a7e7f429b6de3ccd9a9d0/mpscenes/obstacles/dynamic_obstacle.py#L99) and use the function from pybullet `resetBaseVelocity` to reset to a non-zero velocity, so we could just read from pybullet directly and still support moveable obstacles. What do you think?

I agree with that, especially in combination with the movable obstacles issue. After this change in the mpscenes using `resetBaseVelocity`, position and velocity request should directly use pybullet. However, I would like to keep the access to the other goal and obstacle information through the `getattr` function.

For now, I suggest to ignore the movable obstacles and update after https://github.com/maxspahn/motion_planning_scenes/issues/56 is solved.

**Comment by c-salmi** [comment]
Okay, yes that sounds good :+1:

**Comment by maxspahn** [comment]
I actually realized the changes in mpscenes are so minor (litereally one line) that we can wait for that.

**Comment by maxspahn** [comment]
That should do it @c-salmi

**Pull request merged**
