### PR TITLE
Adds docker file and corresponding readme.

### PR DESCRIPTION
**Pull request by rensheemskerk**

### CODE REVIEW

**Comment by maxspahn** [comment]
Actually, this feature has not been integrated in the master branch. 
So I will merge it as soon as the tests have succeeded.

**Review by GijsGroote — COMMENTED** [review]
I've cloned gym_urdf_envs and created the docker with
`docker build -t urdf_gym_docker .`
This took about 2 min 40 sec (No problemo).

Then `xhost +`
then I've tried to run an example using both options provided in the README.md. An error occured: cannot connect to X server. 

Here is my terminator output
[terminator_output.txt](https://github.com/maxspahn/gym_envs_urdf/files/8335392/terminator_output.txt)

Am I incorrectly using the docker? Or should this error not occur? Please eleborate.

**Comment by maxspahn** [comment]
Too bad that this didn't work.
It is surely a problem with the X-server that manages the screen access from different services.
But I am far from being an expert on this. Maybe we could try it out together some afternoon, but for now I have no clever solution to this....

**Comment by maxspahn** [comment]
Changed base branch to develop according to #75.

**Comment by maxspahn** [comment]
Closed due to inactivity and low priority.

**Pull request closed without merging**
