### PR TITLE
Ft multi robots

### PR DESCRIPTION
**Pull request by maxspahn**
Introduces changing the structure to one single environment with given robot instances. 
That also allows having multiple robots in parallel.
Refer to #120 for more information.

### CODE REVIEW

**Comment by c-salmi** [comment]
The test still fails at the obstacle sensor part. However it only fails when running all tests at the same time. Locally running just `pytest test_obstacle_sensor.py` does work, not sure what causes this.

**Comment by maxspahn** [comment]
@c-salmi Now, it seems fine.

**Comment by maxspahn** [comment]
We should still improve the warning when the observation is outside the observation space. It should indicate which robot is the one causing the problem.
You can run the multi_robot example to see the confusing behavior.

**Comment by maxspahn** [comment]
@c-salmi: Could you add an example with the panda robot without the gripper. The naming seems to be causing confusion as there is already a panda robot in the pybullet_data package.

**Review by c-salmi — APPROVED** [review]

**Pull request merged**
