### PR TITLE
Fixes wrong lateral friction for differential drive

### PR DESCRIPTION
**Pull request by maxspahn**
Some users pointed out that the differential drives were not moving in perfect circles when given a constant (turning) velocity command. The problem was related to fricton of the castor wheels.

This PR fixes this for the differential drives. To be investigated whether action needs to be taken for the bicycle model.

### CODE REVIEW

**Comment by maxspahn** [comment]
Before merging this, #132 should be merged to trigger the unit tests here. @c-salmi

**Review by c-salmi — COMMENTED** [review]
I think in general it's good to set the caster wheel joint lateral friction to zero. However, for the Jackal it's not really true to the real world, since the jackal doesn't have caster wheels. It's 4 wheel drive, the front and rear of each side are actuated with the same velocity.

edit: also I've approved #132 so the unit tests can trigger here.

**Comment by maxspahn** [comment]
@c-salmi Thanks for pointing out. So the boxer and the jackal are different in terms of actuated wheels? I'll modify this accordingly.

**Comment by maxspahn** [comment]
@c-salmi I think this is a reasonable workaround.

**Review by c-salmi — APPROVED** [review]
Yes, looks good :+1:

**Pull request merged**
